import { availableParallelism } from 'node:os';
import type { VidimusConfig } from './types.ts';

const halfTheCores = Math.max(2, Math.min(8, Math.floor(availableParallelism() / 2)));

export const DEFAULT_AUDITS = ['i18n', 'csp', 'a11y', 'links', 'r12s'];

export const defaults = (cwd: string): VidimusConfig => ({
  root: cwd,
  distDir: 'dist',
  outDir: '.vidimus',
  port: 4322,
  origin: '',
  siteUrl: '',
  exclude: [],
  locales: [],
  defaultLocale: '',
  allLocales: false,
  routes: {
    paths: [],
    discover: 'off',
    limit: 200,
  },
  render: {
    mode: 'off',
    include: [],
    waitFor: 'load',
    timeout: 30000,
    concurrency: halfTheCores,
  },
  audits: DEFAULT_AUDITS,
  severity: {},
  strict: false,
  ignore: [],
  baseline: {
    file: 'vidimus.baseline.json',
    update: false,
  },
  plugins: [],
  reporters: [],
  browser: {
    args: ['--no-sandbox', '--disable-dev-shm-usage'],
    executablePath: '',
  },
  server: {
    gzip: true,
    headers: [],
    fallback: '',
    fallbackStatus: 200,
  },
  i18n: {
    files: '',
  },
  csp: {
    exclude: [],
    sandbox: true,
  },
  r12s: {
    viewports: [320, 375, 768],
    minTarget: 24,
    minFont: 12,
    concurrency: halfTheCores,
    timeout: 60_000,
    exclude: [],
  },
  a11y: {
    standard: 'WCAG2AA',
    timeout: 60_000,
    concurrency: 1,
    exclude: [],
    hideElements: '',
    ignore: [],
  },
  shots: {
    outDir: 'shots',
    baselineDir: '',
    viewports: [{ width: 375, height: 667 }, 1280],
    exclude: [],
    sample: [],
    allLocales: false,
    motion: { interval: 100, stableFrames: 5, maxFrames: 60 },
    mask: [],
    maskEmbeds: true,
    freeze: true,
    concurrency: halfTheCores,
    tolerance: 12,
    maxDiff: 0.002,
    settleTimeout: 10_000,
    protocolTimeout: 600_000,
    updateBaseline: false,
  },
  lighthouse: {
    outDir: 'lighthouse',
    exclude: [],
    sample: [],
    all: false,
    urls: [],
    thresholds: { performance: 0.9, accessibility: 1, 'best-practices': 0.9, seo: 1 },
    overrides: [],
  },
  links: {
    skip: ['^mailto:', '^tel:'],
    concurrency: 25,
    timeout: 20_000,
    checkExternal: true,
    retry: true,
    notFound: {
      selector: '',
      text: '',
    },
  },
  seo: {
    exclude: ['^/404(\\.html|/)?$'],
    allowNoindex: [],
    titleLength: { min: 10, max: 60 },
    descriptionLength: { min: 50, max: 160 },
    canonical: true,
    h1: true,
    sitemap: true,
    robots: true,
    orphans: true,
  },
  security: {
    file: '_headers',
    exclude: [],
    require: {
      'strict-transport-security': 'max-age=(3[1-9]\\d{6}|[4-9]\\d{7}|\\d{9,})',
      'x-content-type-options': '^nosniff$',
      'referrer-policy': '^(?!.*(unsafe-url|no-referrer-when-downgrade)).+$',
      'permissions-policy': '',
    },
    clickjacking: true,
    unsafeInline: true,
    mixedContent: true,
    sri: true,
    securityTxt: true,
  },
  privacy: {
    allow: [],
    exclude: [],
    sample: [],
    allLocales: false,
    cookies: true,
    wait: 1500,
    concurrency: halfTheCores,
    timeout: 60_000,
  },
  html: {
    exclude: [],
    extends: ['html-validate:standard'],
    rules: {},
  },
  budget: {
    exclude: [],
    html: 100_000,
    css: 100_000,
    js: 250_000,
    image: 500_000,
    page: 2_000_000,
    legacyImage: 100_000,
    dimensions: true,
  },
  assets: {
    exclude: ['^/404(\\.html|/)?$'],
    favicon: true,
    manifest: true,
    openGraph: true,
    ogImage: { width: 1200, height: 630 },
    notFound: true,
    adsTxt: 'auto',
    changePassword: 'auto',
    appleAppSiteAssociation: 'auto',
    assetLinks: 'auto',
  },
});
